### ISSUE TITLE
Improve GPDR concent during registration

### ISSUE THREAD

**Issue by lsolesen** [vejle-idraetshoejskole/web#31]
![screenshot 1](https://user-images.githubusercontent.com/148026/45752620-63889d00-bc16-11e8-8730-2d8a2f00e3f3.png)

Særskilt samtykke til markedsføring - med Ja og Nej på korte kurser. På korte kurser bliver det for alle og til sidst. Se eksempel nedenunder fra Brandbjerg.

![screenshot](https://user-images.githubusercontent.com/148026/45752613-5ff51600-bc16-11e8-86a9-28c1a4d0087a.png)

Der oprettes frifelt i EDBBrugsen / KomIT  til Markedsføring,

**Comment by franzskaaning** [comment]
@lsolesen vedr. EDBBrugsen, skal data også sendes med der?

Vi bruger ca samme funktion på events. Men dette er kun for korte kurser. Korrekt?
