### ISSUE TITLE
Mange indtaster kun en voksen på vies.dk/ansogning

### ISSUE THREAD

**Issue by lsolesen** [vejle-idraetshoejskole/web#39]
Vi skal gøre det mere sædvanligt, at man indtaster to voksne på vies.dk. Kan vi forbedre flowet en lille smule?

**Comment by franzskaaning** [comment]
Indsæt tekst i ramme på bekræftelsesside "Der er tilføjet en forælder/værge, tilføj flere".

Teksten vises kun hvis der kun er tilføjet en enkelt forælder.
